[package]
name = "glider"
version = "0.1.0"
authors = ["Alexandre Hamez <alexandre.hamez@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "4.0.27", features = ["derive"] }

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["ttf", "bundled"]
